# Configuration file for Active Learning experiments

experiments:
  # New Data format
  - name: Random
    embeddings_dir: ESC10_BASEAL/embeddings/birdnet/
    annotations_path: ESC10_BASEAL/labels.csv
    hidden_dim: null
    sampling_strategy: random
    learning_rate: 0.001
    repeats: 2
    device: cpu
    pretrain_samples: null 

  - name: Random (ESC50)
    embeddings_dir: ESC50_BASEAL/embeddings/birdnet/
    annotations_path: ESC50_BASEAL/labels.csv
    hidden_dim: null
    sampling_strategy: margin
    learning_rate: 0.001
    repeats: 2
    device: cpu
    pretrain_samples: null 

  # - name: Margin
  #   embeddings_dir: ESC10_BASEAL/embeddings/birdnet/
  #   annotations_path: ESC10_BASEAL/labels.csv
  #   hidden_dim: null
  #   sampling_strategy: margin
  #   learning_rate: 0.001
  #   repeats: 2
  #   device: cpu
  #   pretrain_samples: null 